# Generated by Django 6.0.2 on 2026-02-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
